### ISSUE TITLE
monitor panes do not refresh after a restart for very large migration

### ISSUE THREAD

**Issue by toddoconnor** [timrogers/github-migration-monitor#96]
I was migrating over 2,500 very small repos in parallel. Starting github-migration-monitor at the start of the migration there was no problem. Panes were filling out and data was being displayed.

I then stopped the monitor to take a break. When trying to resume the monitor none of the top panes filled out. Only the Event Log pane was showing data and very slowly at that. 

Could this be a scale issue due to the large number of migrations?

**Comment by timrogers** [comment]
@toddoconnor 👋 Certainly possible - I haven't tested it with that kind of large number of migrations, but I can do. I'd imagine there would be easy-ish performance wins.

So just to confirm, the event log was still moving, but the top panes were empty?

Do you have a screenshot of what the UI looked like so I can better understand the failure mode? Obviously, feel free to redact it!

**Comment by toddoconnor** [comment]
Hi @timrogers We're migrating less than 80 repos this morning and we're about 30 minutes in. Here's a screen shot of when we fire up the monitor. All panes are blank except for some in the event log.

<img width="1239" alt="Screenshot 2023-11-04 at 9 06 30 AM" src="https://github.com/timrogers/github-migration-monitor/assets/103966065/82c256e9-1b32-44ef-8c99-5dca235fee49">

**Comment by timrogers** [comment]
Interesting! I think this is an issue with the API timing out. 

I'd like to take a look in the logs. Can you double check what user owns the PAT you're using for the tool, and share the username with me? Up to you if you want to share it publicly or email the address on my profile ☺️

**Comment by timrogers** [comment]
I'm going to close this now - the underlying issue was API timeouts, and this has just been fixed by GitHub, so we should see better performance going forward 🥳
